<?php

    $authors = $uid = $display_tags = '';

    if ($entry->authors) {
        $authors = sprintf(' by <span class="p-author">%s</span>', htmlspecialchars($entry->authors));
    }

    if ($entry->doi) {
        $uid = sprintf(' <span class="isbn p-uid">doi:%s</span>', $entry->doi);
    } elseif ($entry->isbn) {
        $uid = sprintf(' <span class="isbn">ISBN: <a href="%s" class="p-uid">%s</a></span>',
            $utils->router->pathFor('isbn', ['isbn' => $entry->isbn]),
            htmlspecialchars($entry->isbn)
        );
    }

    if ($entry->category) {
        $tags = explode(',', $entry->category);
        foreach ($tags as $tag) {
            $display_tags .= sprintf('<span class="p-category">%s</span>, ', htmlspecialchars($tag));
        }
        $display_tags = sprintf('<div class="tags">Tags: %s</div>', trim($display_tags, ', '));
    }

    $entry_date = $utils->get_entry_date($entry);
    $entry_url = $utils->get_entry_url($entry, $user);
?>

<li class="h-entry">

<?php $this->import('partials/author-block', ['entry' => $entry, 'user' => $user]); ?>

    <div class="content">

        <div class="summary p-summary">
            <?=$utils->get_read_status_microformat($entry->read_status);?>: <span class="p-read-of h-cite"><cite class="p-name"><?=htmlspecialchars($entry->title);?></cite><?=$authors;?><?=$uid;?></span>

        </div>
        <div class="date">
            <a href="<?= $entry_url; ?>" class="<?= $utils->get_url_microformats($entry); ?>"><time class="dt-published" datetime="<?= $entry_date->format('Y-m-d H:i:sP') ?>"><?= $entry_date->format('F j, Y g:ia P') ?></time></a>
        </div>
        <?=$display_tags;?>

    </div>

</li>

