
    <header>
        <!-- Book by Beth Bolton from the Noun Project https://thenounproject.com/icon/1727889/ -->
        <a href="/"><img src="/images/book.svg" alt=""></a>
        <a href="/">indiebookclub</a>
    </header>

    <div class="user-bar" style="text-align: right;">

<?php if ($utils->session('me')): ?>
    Signed in as <?php if ($utils->session('display_photo')): ?> <img src="<?=$utils->session('display_photo')?>" alt="profile photo for" style="height: 1em;"> <?php endif; ?> <b><?=$utils->session('display_name');?></b> • <a href="<?=$utils->router->pathFor('profile', ['domain' => $utils->hostname($utils->session('me'))]);?>">My Profile</a> • <a href="<?=$utils->router->pathFor('signout');?>">Sign Out</a>
<?php else: ?>
    <a href="/">Sign In</a>
<?php endif; ?>

    </div>

