<?php

declare(strict_types=1);

use Dotenv\Dotenv;

require __DIR__ . '/vendor/autoload.php';

$environments = Dotenv::createArrayBacked(__DIR__)->load();

# construct env.php contents
$output = '<?php' . PHP_EOL . PHP_EOL;
$output .= '### Do not update this file. This file is automatically generated during deployment. ###' . PHP_EOL . PHP_EOL;

foreach ($environments as $key => $value) {
    $output .= sprintf('$_ENV[\'%s\'] = "%s";',
        $key,
        $value
    ) . PHP_EOL;
}

$output .= sprintf('$_ENV[\'ENV_GENERATED\'] = "%s";',
    date('Y-m-d H:i:s')
) . PHP_EOL;

# write env.php
$filename = __DIR__ . '/app/env.php';
if (!file_exists($filename) || false === file_put_contents($filename, $output)) {
    echo 'Error deploying environments file' . PHP_EOL;
    exit;
}

echo 'Deployed successfully' . PHP_EOL;

