
<?php $this->import('partials/header'); ?>

<div class="content h-entry">

    <h2 class="p-name"> About indiebookclub </h2>

    <div class="e-content">

        <p> <span class="p-summary">indiebookclub is an app for keeping track of the books you are reading or want to read.</span> It is primarily intended to help you <a href="https://indieweb.org/own_your_data">own your data</a> by posting directly to your own site with <a href="https://micropub.net">Micropub</a>. If your site does not support Micropub yet, you can still post to your indiebookclub profile. </p>

        <p> If you are using Micropub, your posts will be linked to the canonical copy on your site. There are no plans to make indiebookclub a complex social network, but I might add features like a stream of newly-added books. </p>

        <h3> The Name </h3>

        <p> During <a href="https://indieweb.org/2018/Baltimore">IndieWebCamp Baltimore 2018</a>, <a href="https://martymcgui.re" class="h-card">Marty McGuire</a> made a comment that he will be more interested in indieweb <i><a href="https://indieweb.org/read">read</a></i> posts when there’s “some aggregator like indiebookclub dot biz.” That domain name was obviously a joke, but that has rarely stopped me before. </p>

        <h3> Credits </h3>

        <p> Inspired by and using open source code from <a href="https://aaronparecki.com" class="h-card">Aaron Parecki</a>’s <a href="https://teacup.p3k.io">Teacup</a> and <a href="https://quill.p3k.io/">Quill</a>. </p>

        <p> “<a href="https://thenounproject.com/icon/1727889/">Book</a>” icon by Beth Bolton from <a href="http://thenounproject.com/">the Noun Project</a>. </p>

        <p> Maintained by <a href="https://gregorlove.com" class="h-card">gRegor Morrill</a>. </p>

    </div>

</div>

