
<?php $this->import('partials/header'); ?>

<div class="content">
    <h2> Are you sure you want to delete this post? </h2>

    <ul class="entries">

<?php
$is_caching = true;
$this->import('partials/entry', compact('entry', 'profile', 'is_caching'));
?>

    </ul>

    <div class="alert alert-warning">
        Check the box below to confirm you want to delete this post.<br>
        If you don’t want to delete, you can <b><a href="<?=$utils->router->pathFor('profile', ['domain' => $utils->hostname($utils->session('me'))])?>">cancel and return to your profile</a></b>.
    </div>

<?php
if ($is_micropub_post && !$has_micropub_delete):
?>

    <div class="alert alert-warning">
        Optional: If you would like to also delete this post from your site, indiebookclub will need additional permission: <b><a href="<?= $utils->router->pathFor('auth_re_authorize') ?>">Re-authorize to add delete permission</a></b>
    </div>

<?php
endif;
?>

    <form method="post" action="<?=$utils->router->pathFor('delete');?>">
        <input type="hidden" name="confirm_delete" value="no">
        <p> <label><input type="checkbox" name="confirm_delete" value="yes" required> Yes, delete this post from indiebookclub</label> </p>

        <input type="hidden" name="mp_delete" value="no">

<?php
if ($is_micropub_post && $has_micropub_delete):
?>

        <p>
            <label><input type="checkbox" name="mp_delete" value="yes"> Delete this post from my site as well (optional)</label>
            <span class="help-block">This will send a Micropub delete request to your site</span>
        </p>

<?php
endif;
?>

        <input type="submit" value="Delete">
        <input type="hidden" name="id" value="<?=$entry->id;?>">
    </form>

</div>

