
<?php $this->import('partials/header'); ?>

<div class="content h-feed">
<?php if ($utils->session('me')): ?>
    <form method="get" action="/new" style="text-align: center;"><button>New Post</button></form>
<?php endif; ?>

    <h2 class="p-name"><?=$feed_name;?></h2>

    <ul class="entries">

<?php
foreach ($entries as $entry) {
    if ($entry->visibility == 'private' && $utils->session('user_id') !== $entry->user_id) {
        continue;
    }

    $this->import('partials/entry', compact('entry', 'profile'));
}
?>

    </ul>

<?php if (count($entries) == 0): ?>
    <p>There are no entries yet!</p>
<?php endif; ?>

    <nav class="entries-navigation">
        <div class="older">

<?php
    $profile_url = $utils->router->pathFor('profile', ['domain' => $profile->profile_slug]);

    if ($older) {
        echo sprintf('<a href="%s?before=%s" rel="prev">← Older</a>', $profile_url, $older);
    }
?>

        </div>

        <div class="newer">

<?php
    if ($newer) {
        echo sprintf('<a href="%s?before=%s" rel="next">Newer →</a>', $profile_url, $newer);
    }
?>

        </div>
    </nav>
</div>

