<div class="h-x-app h-app">
    <div class="masthead">
        <img src="/images/book.svg" class="u-logo" alt="">
        <h1 class="p-name"> indie<span class="logo-text-book">book</span>club </h1>
    </div>

    <div class="content">
        <p class="tagline p-summary">indiebookclub is a simple app for tracking books you are reading.</p>

        <p>To use indiebookclub, sign in with your domain. If your website supports <a href="https://micropub.net">Micropub</a>, it will post directly to your site. Otherwise, it will post to your profile on this website.</p>

<?php if ($utils->session('me')): ?>

        <p> You are signed in as <b><?= $utils->hostname($utils->session('me')); ?></b>. <a href="<?=$utils->router->pathFor('profile', ['domain' => $utils->hostname($utils->session('me'))]);?>">My Profile</a> • <a href="<?=$utils->router->pathFor('signout');?>">Sign Out?</a> </p>

        <form method="get" action="/new" style="text-align: center;"><button>New Post</button></form>

<?php else: ?>

        <form action="<?=$utils->router->pathFor('auth_start');?>" method="get" class="sign-in">
            <input type="text" name="me" placeholder="https://example.com" required>
            <input type="submit" value="Sign In">
        </form>

<?php endif; ?>

    </div>
</div>

