
	<?php $this->import('partials/header'); ?>

	<div class="h-feed">

		<h2 class="feed-name p-name"> Entries for ISBN <?=htmlspecialchars($isbn);?> </h2>

		<ul class="entries">

<?php
	foreach ($entries as $entry) {
		$this->import('partials/entry', ['entry' => $entry, 'user' => null]);
	}
?>
		</ul>

	</div>

	<nav class="entries-navigation">
		<div class="older">
<?php
	$isbn_url = $utils->router->pathFor('isbn', ['isbn' => $isbn]);

	if ($older) {
		echo sprintf('<a href="%s?before=%s" rel="prev">← Older</a>', $isbn_url, $older);
	}
?>
		</div>

		<div class="newer">
<?php
	if ($newer) {
		echo sprintf('<a href="%s?before=%s" rel="next">Newer →</a>', $isbn_url, $newer);
	}
?>
		</div>
	</nav>

