
		<?php $this->import('partials/header'); ?>

		<div class="content">
		<h2 class="util-no-margin"> New Post </h2>

<?php
	if ($errors) {
		$word_errors = (count($errors) == 1) ? 'error' : 'errors';
		echo '<div class="attention">';
		echo sprintf('<p> Please fix the following %s and re-submit the form: </p>', $word_errors);
		echo '<ul>';
		foreach ($errors as $error) {
			echo sprintf('<li> %s </li>', $error);
		}
		echo '</ul>';
		echo '</div>';
	}

	$options_read_status = [
		'to-read' => 'Want to read',
		'reading' => 'Currently reading',
		'finished' => 'Finished reading',
	];
	$display_read_status_options = '';

	foreach ($options_read_status as $value => $label) {
		$selected = $utils->markSelected($value, $read_status, false);
		$display_read_status_options .= sprintf('<option value="%s"%s>%s</option>',
			$value,
			$selected,
			$label
		);
	}

	$checked_doi = ($read_doi) ? ' checked' : '';
	$checked_isbn = (!$checked_doi || $read_isbn) ? ' checked' : '';
?>

		<form method="post" action="<?=$utils->router->pathFor('new');?>" style="margin-top: 20px;">

			<p>
				<label for="i_read_status">Read Status:</label>
				<select name="read_status" id="i_read_status" class="util-full-width" required>
					<option value=""></option>
					<?=$display_read_status_options;?>
				</select>
			</p>

			<p>
				<label for="i_title">Title:</label>
				<input type="text" name="title" id="i_title" value="<?=$read_title;?>" class="util-full-width" required>
			</p>

			<p>
				<label for="i_authors">Author(s):</label> (optional)
				<input type="text" name="authors" id="i_authors" value="<?=$read_authors;?>" class="util-full-width">
			</p>

			<input type="radio" name="switch-uid" id="show-isbn"<?=$checked_isbn;?>><label for="show-isbn" class="toggle-label">Use ISBN</label>
			<input type="radio" name="switch-uid" id="show-doi"<?=$checked_doi;?>><label for="show-doi" class="toggle-label">Use DOI Name</label> &nbsp;

			<p class="doi-fieldset">
				<label for="i_doi">DOI Name:</label> (optional)
				<input type="text" name="doi" id="i_doi" value="<?=$read_doi;?>" class="util-full-width">
			</p>

			<p class="isbn-fieldset">
				<label for="i_isbn">ISBN:</label> (optional)
				<span class="help-block">ISBN-13 preferred — ISBN-10 will be converted to ISBN-13.</span>
				<input type="text" name="isbn" id="i_isbn" value="<?=$read_isbn;?>" class="util-full-width">
			</p>

			<p>
				<label for="i_tags">Tags:</label> (optional)
				<span class="help-block">Separate tags with commas</span>
				<input type="text" name="tags" id="i_tags" value="<?=$read_tags;?>" class="util-full-width">
			</p>

			<p>
				<details> <summary>Advanced</summary>
					<label for="i_tzoffset">Your UTC timezone offset:</label>
					<input type="text" name="tzoffset" id="i_tzoffset" size="10" value="">
				</details>
			</p>

			<input type="submit" value="Submit" class="btn btn-primary">

			<div id="entry-buttons"></div>

		</form>

		<?php if ($micropub_endpoint): ?>
		<div class="callout">

			<p>Clicking <b>Submit</b> will post a <a href="https://indieweb.org/read" target="_blank" rel="noopener">read</a> post to your Micropub endpoint: <b><?= $micropub_endpoint ?></b></P>

			<p>See the <a href="<?=$utils->router->pathFor('documentation');?>#micropub">documentation</a> for more information about the request that will be sent.</p>

			<p>If you are experiencing problems with posts not showing up on your site, check the <a href="<?=$utils->router->pathFor('settings');?>">settings</a> page for more information, including the last response from your micropub endpoint.</p>

		</div>
		<?php endif; ?>

	</div>

<script>
$(function(){

	function tz_seconds_to_offset(seconds) {
		var tz_offset = '';
		var hours = zero_pad(Math.floor(Math.abs(seconds / 60 / 60)));
		var minutes = zero_pad(Math.floor(seconds / 60) % 60);
		return (seconds < 0 ? '-' : '+') + hours + ":" + minutes;
	}

	function zero_pad(num) {
		num = "" + num;
		if (num.length == 1) {
			num = "0" + num;
		}
		return num;
	}

	var d = new Date();
	$('#i_tzoffset').val(tz_seconds_to_offset(d.getTimezoneOffset() * 60 * -1));
});
</script>

