<?php
    $display_extra_headers = '';
    if (isset($extra_headers) && is_array($extra_headers)) {
        $display_extra_headers = "\n" . implode($extra_headers, "\n");
    }
?><!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?=$title;?></title>
    <link rel="icon" href="/images/book.png">
    <link rel="apple-touch-icon-precomposed" href="/images/book.png" />
    <link rel="stylesheet" href="/css/style.css">
    <script src="/js/jquery-1.7.1.min.js"></script><?=$display_extra_headers;?>

</head>

<body>

    <div class="container">
<?php echo $mainContent; ?>
    </div>

<?php
    if (!isset($footer) || $footer) {
        $this->import('partials/footer');
    }
?>
</body>
</html>

